on:
  workflow_call:
    inputs:
      project:
        description: 'Project to run deployment against'
        required: true
        type: string
      environment:
        description: 'Environment to run deployment against'
        type: environment
        required: true

jobs:
  deploy:
    name: Deploy ${{ inputs.project }} ${{ inputs.environment }}
    needs: test
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}
      url: 'https://wally.best'

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.project }}-${{ inputs.environment }}
        path: ./${{ inputs.project }}/dist

    - name: Debug
      run: |
        cat ./${{ inputs.project }}/dist/config.template
        cat ./${{ inputs.project }}/dist/config.js
