name: WebApp

on:
  push:
    branches:
      - "master"
    paths:
      - "src/**"
      - ".github/workflows/*.yml"
  pull_request:
    branches:
      - "master"
    paths:
      - "src/**"
      - ".github/workflows/*.yml"

env:
  AZURE_B2C_CLIENT_ID: ${{ vars.AZURE_B2C_CLIENT_ID }}
  AZURE_B2C_AUTHORITY_URL: ${{ vars.AZURE_B2C_AUTHORITY_URL }}
  AZURE_B2C_SCOPE: ${{ vars.AZURE_B2C_SCOPE }}

jobs:
  build:
    uses: ./.github/workflows/build-node.yml
    with:
      project: my-vite4-react-ts-app

  test:
    uses: ./.github/workflows/test-node.yml
    needs: build
    with:
      project: my-vite4-react-ts-app

  publish:
    uses: ./.github/workflows/publish-node.yml
    secrets: inherit
    needs: test
    with:
      project: my-vite4-react-ts-app
      environment: tst

  deploy:
    uses: ./.github/workflows/publish-node.yml
    secrets: inherit
    needs: publish
    with:
      project: my-vite4-react-ts-app
      environment: tst
