name: WebApp

on:
  push:
    branches:
      - "master"
    paths:
      - "src/**"
      - ".github/workflows/*.yml"
  pull_request:
    branches:
      - "master"
    paths:
      - "src/**"
      - ".github/workflows/*.yml"

jobs:
  build:
    uses: ./.github/workflows/build-node.yml
    with:
      project: my-vite4-react-ts-app

  test:
    uses: ./.github/workflows/test-node.yml
    needs: build
    with:
      project: my-vite4-react-ts-app

  publish-dev:
    uses: ./.github/workflows/publish-node.yml
    secrets: inherit
    needs: test
    with:
      project: my-vite4-react-ts-app
      environment: dev

  publish-tst:
    uses: ./.github/workflows/publish-node.yml
    secrets: inherit
    needs: test
    with:
      project: my-vite4-react-ts-app
      environment: tst

  publish-prd:
    uses: ./.github/workflows/publish-node.yml
    secrets: inherit
    needs: test
    with:
      project: my-vite4-react-ts-app
      environment: prd

  deploy-dev:
    uses: ./.github/workflows/publish-node.yml
    secrets: inherit
    needs: publish-dev
    with:
      project: my-vite4-react-ts-app
      environment: dev

  deploy-tst:
    uses: ./.github/workflows/publish-node.yml
    secrets: inherit
    needs: deploy-dev
    with:
      project: my-vite4-react-ts-app
      environment: tst

  deploy-prd:
    uses: ./.github/workflows/publish-node.yml
    secrets: inherit
    needs: deploy-tst
    with:
      project: my-vite4-react-ts-app
      environment: prd
